# Generated by Django 5.2.13 on 2026-04-27 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_reserva_pagamento_whatsapp'),
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesaRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True)),
                ('codigo_qr', models.CharField(max_length=30, unique=True)),
                ('estado', models.CharField(choices=[('livre', 'Livre'), ('ocupada', 'Ocupada'), ('aguardando_atendimento', 'Aguardando atendimento')], default='livre', max_length=30)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.AddField(
            model_name='pedidorestaurante',
            name='cliente_nome',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='pedidorestaurante',
            name='cliente_telefone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='pedidorestaurante',
            name='metodo_pagamento',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='pedidorestaurante',
            name='observacoes',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='pedidorestaurante',
            name='origem',
            field=models.CharField(choices=[('quarto', 'Pedido do quarto'), ('presencial', 'Pedido presencial'), ('mesa_qr', 'Pedido por QR Code')], default='quarto', max_length=20),
        ),
        migrations.AddField(
            model_name='pedidorestaurante',
            name='pago_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidorestaurante',
            name='qr_code_usado',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='pedidorestaurante',
            name='tempo_estimado_min',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='produtorestaurante',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='produtorestaurante',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produtorestaurante',
            name='imagem_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='produtorestaurante',
            name='tempo_preparo_min',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='pedidorestaurante',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_restaurante', to='reservas.reserva'),
        ),
        migrations.AlterField(
            model_name='pedidorestaurante',
            name='status',
            field=models.CharField(choices=[('recebido', 'Recebido'), ('aceite', 'Aceite'), ('em_preparacao', 'Em preparacao'), ('pronto', 'Pronto'), ('entregue', 'Entregue'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='recebido', max_length=20),
        ),
        migrations.AddField(
            model_name='pedidorestaurante',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='restaurante.mesarestaurante'),
        ),
    ]
