# Generated by Django 5.2.13 on 2026-04-27 16:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_mesarestaurante_pedidorestaurante_cliente_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidorestaurante',
            name='estoque_baixado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produtorestaurante',
            name='controla_estoque',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produtorestaurante',
            name='estoque_atual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='produtorestaurante',
            name='estoque_minimo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.CreateModel(
            name='MovimentoEstoqueRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste', 'Ajuste'), ('reposicao', 'Reposição')], max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_estoque', to='restaurante.pedidorestaurante')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_estoque', to='restaurante.produtorestaurante')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
