# Generated by Django 5.2.13 on 2026-04-24 14:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0007_reserva_pagamento_whatsapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('comentario', models.TextField()),
                ('avaliacao', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('oculto', 'Oculto')], default='pendente', max_length=20)),
                ('publicado', models.BooleanField(default=False)),
                ('abusivo', models.BooleanField(default=False)),
                ('motivo_moderacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depoimentos', to='reservas.reserva')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depoimentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('user', 'reserva'), name='uniq_depoimento_por_user_reserva')],
            },
        ),
    ]
