# Generated by Django 5.2.13 on 2026-04-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('andar', models.PositiveSmallIntegerField(default=1)),
                ('tipo', models.CharField(max_length=30)),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('disponivel', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['andar', 'codigo'],
            },
        ),
    ]
