# Generated by Django 5.2.13 on 2026-04-20 21:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoLimpeza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('normal', 'Normal'), ('profunda', 'Profunda'), ('checkout', 'Checkout')], default='normal', max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_curso', 'Em curso'), ('concluido', 'Concluido'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_limpeza', to='reservas.reserva')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
