# Generated by Django 5.2.13 on 2026-04-20 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faturacao', '0001_initial'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fatura', to='reservas.reserva'),
        ),
        migrations.AddField(
            model_name='itemfatura',
            name='fatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='faturacao.fatura'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='fatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='faturacao.fatura'),
        ),
    ]
