# Generated by Django 5.2.13 on 2026-04-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturacao', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=20),
        ),
    ]
