# Generated by Django 5.2.13 on 2026-04-24 15:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturacao', '0003_pagamento_status'),
        ('reservas', '0007_reserva_pagamento_whatsapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faturas_emitidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fatura',
            name='emitido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturas_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fatura',
            name='enviado_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fatura',
            name='enviado_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fatura',
            name='metodo_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fatura',
            name='numero_fatura',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fatura',
            name='pago_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='data_emissao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturas', to='reservas.reserva'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='status',
            field=models.CharField(choices=[('emitida', 'Emitida'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], default='emitida', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemfatura',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='itemfatura',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
