# Generated by Django 5.2.13 on 2026-04-24 16:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturacao', '0004_fatura_cliente_fatura_emitido_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='fatura',
            name='estado_pagamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('validado', 'Validado')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='fatura',
            name='observacoes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='fatura',
            name='referencia_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fatura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='fatura',
            name='tipo',
            field=models.CharField(choices=[('reserva', 'Fatura de reserva'), ('sinal', 'Fatura de sinal'), ('integral', 'Fatura de pagamento integral'), ('servicos', 'Fatura de serviços'), ('complementar', 'Fatura complementar'), ('final', 'Fatura final')], default='reserva', max_length=20),
        ),
        migrations.AddField(
            model_name='fatura',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='fatura',
            name='valor_pendente',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='itemfatura',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_fatura_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemfatura',
            name='motivo_ajuste',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='itemfatura',
            name='origem_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemfatura',
            name='origem_tipo',
            field=models.CharField(choices=[('reserva', 'Reserva'), ('limpeza', 'Limpeza'), ('lavandaria', 'Lavandaria'), ('restaurante', 'Restaurante'), ('extensao', 'Extensão'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
    ]
