# Generated by Django 5.2.13 on 2026-04-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente', 'Pendente'), ('aguardando_pagamento', 'Aguardando pagamento'), ('aguardando_confirmacao', 'Aguardando confirmacao'), ('confirmada', 'Confirmada'), ('ativa', 'Ativa'), ('concluida', 'Concluida'), ('cancelada', 'Cancelada')], default='rascunho', max_length=30),
        ),
    ]
